resources:
  - name: source-code
    type: git
    source:
      branch: master
      private_key: |
      uri: git@github.com:naveensrivatsa/linux2.git

jobs:
  - name: create-hardened-ami-image
    plan:
    - get: source-code
    - task: packer-build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: amazonlinux
            tag: latest
            username: 
            password: 
        inputs:
          - name: source-code
        run:
          dir: source-code
          path: sh
          args:
          - -exc
          - |
            yum update -y
            yum install -y yum-utils
            yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            yum -y install packer
            amazon-linux-extras install ansible2 -y
            packer build \
              -var 'aws_access_key=' \
              -var 'aws_secret_key=' \
              -var 'ssh_username=ec2-user' \
              template.json