- name: dconf_update
  command: dconf update
- name: auditd_restart
  command: service auditd {{ item }}
  with_items:
    - stop
    - start
- name: ssh_restart
  service:
    name: sshd
    state: restarted
- name: do_reboot
  reboot:
    pre_reboot_delay: 60
