---
- hosts: all
  gather_facts: false
  become: yes
  become_user: root

  tasks:
    - name: include_role 'rhel7STIG'
      include_role:
        name: rhel7STIG
#     - include_role:
#         name: ./ami-scan
